# Site settings
title: "Khalid Portfolio"
description: "An interactive showcase of Khalid Rizvi's extensive technical skills and experiences, hosted with Jekyll and GitHub Pages."


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Khalid Rizvi"
resume_title:                   "Excellence through innovation."

# used for the contact button in _layouts/resume.html
resume_contact_email:           "khalid.rizvi@icloud.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "703-656-6394"
resume_contact_address:         "9821 Spring Ridge Lane, Vienna, VA 22182"

resume_header_contact_info:     "703-656-6394 • khalid.rizvi@icloud.com"
display_header_contact_info:    "true"

resume_header_intro: >
  <p>With a professional journey spanning several decades, I've
  distinguished myself not just as a transformative technical leader
  but as a hands-on innovator in the heart of technology evolution. My
  approach is immersive: I delve into narratives, internalizing the
  essence of challenges, before meticulously designing solutions using
  my favored programming paradigms. This depth of understanding
  facilitates the implementation phase, where I sculpt these designs
  into tangible solutions using adept software programming languages.
  I've notably championed pivotal 'Lift and Shift' transformations,
  seamlessly migrating legacy systems to cloud infrastructures, and led
  the strategic design and deployment of sophisticated interfaces,
  ensuring data consistency and integration. My expertise has
  frequently been tapped to spearhead complex system integrations and
  design innovative data acquisition solutions. A highlight of my
  journey was the strategic revamp of a prominent search functionality,
  replacing traditional mechanisms with advanced solutions, thereby
  enhancing user accessibility. I also ventured into entrepreneurial
  pursuits, founding and developing a comprehensive wedding planning
  platform, emphasizing my prowess in web technologies and cloud
  services. Throughout my career, I've ensured that my solutions lead
  to process optimizations, scalable architectures, and revenue growth.
  My passion goes beyond architecting solutions; I'm deeply committed
  to mentoring and educating, always eager to guide teams and clients
  towards realizing the full potential of technological solutions. My
  expansive skill set encompasses everything from functional
  programming, web technologies, cloud services, to data streaming and
  visualization.</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/krizvi"
  #  resume_twitter_url:           "http://twitter.com/jglovier"
  #  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/khalidrizvi"
  resume_website_url:           "http://khalidrizvi.com"
  resume_medium_url:            "https://medium.com/@krizvi"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
