# Site settings
title: "Khalid Portfolio"
description: "An interactive showcase of Khalid Rizvi's extensive technical skills and experiences, hosted with Jekyll and GitHub Pages."


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "false"
resume_name: "Jarry Rizvi"
resume_title: "Innovator. Developer. Trailblazer."

# used for the contact button in _layouts/resume.html
resume_contact_email: "jarry.a.rizvi@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "(917)378-4885"
resume_contact_address: "Hicksville, NY 11040"

resume_header_contact_info: "(917)378-4885 • jarry.a.rizvi@gmail.com"
display_header_contact_info: "true"

resume_header_intro: >
  resume_header_intro: >
    <p>Passionate <strong>Full Stack Developer</strong> 
    and <strong>Cloud Engineer</strong> with over <strong>5 years</strong> 
    of experience, driven by an insatiable desire to learn and innovate. 
    My journey, reminiscent of the tale of the lion and the mouse, 
    showcases my ability to think differently and make impactful 
    contributions, no matter the scale. Certified in 
    <strong>AWS Solutions Architect- Associate</strong> and 
    <strong>CompTIA Security+ ce</strong>, I am looking for an opportunity where I am challenged to grow and have a proven track record 
    in cloud engineering, mobile native development, and problem-solving. 
    My goal is to leverage my diverse technical skills and certifications 
    to drive innovation, ensuring the delivery of scalable and secure 
    solutions that align with business objectives.</p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: false
resume_section_skills: true
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/krizvi"
  #  resume_twitter_url:           "http://twitter.com/jglovier"
  #  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/khalidrizvi"
  resume_website_url: "http://khalidrizvi.com"
  resume_medium_url: "https://medium.com/@krizvi"
resume_print_social_links: false

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
