# Site settings
title: "Khalid Portfolio"
description: "An interactive showcase of Khalid Rizvi's extensive technical skills and experiences, hosted with Jekyll and GitHub Pages."


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Khalid Rizvi"
resume_title:                   "Excellence through innovation."

# used for the contact button in _layouts/resume.html
resume_contact_email:           "khalid.rizvi@icloud.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "703-656-6394"
resume_contact_address:         "9821 Spring Ridge Lane, Vienna, VA 22182"

resume_header_contact_info:     "703-656-6394 • khalid.rizvi@icloud.com"
display_header_contact_info:    "true"

resume_header_intro: >
  <p>Over a rich tapestry of decades in the tech industry, I've emerged not 
  just as a transformative <strong>technical leader</strong>, but as a hands-on 
  technological artisan. My engagement with projects is not cursory. Instead, 
  I delve into the narratives of challenges, ensuring that I internalize the 
  very essence before crafting the apt solution.</p>

  <p>It is this deep-seated understanding that has enabled me to lead pivotal 
  <strong>'Lift and Shift'</strong> transformations, offering legacy systems a 
  new lease on life in cloud landscapes. My expertise in strategic interface 
  design and deployment stands as testimony to my ability to foresee and ensure 
  data consistency and robust integration.</p>

  <p>In my endeavors, I've steered teams towards the integration of intricate 
  systems, and pioneered data acquisition innovations, ensuring that businesses 
  remain at the cusp of technological advancements. A salient point in my career 
  has been the transformation of search functionalities - shifting from 
  traditional mechanisms to advanced, user-friendly solutions.</p>

  <p>However, my professional journey isn't limited to roles; I took the 
  entrepreneurial plunge, founding and sculpting a comprehensive <strong>wedding 
  planning platform</strong>, highlighting my prowess in cutting-edge web 
  technologies and cloud services. These achievements don't stand in isolation. 
  Every solution I've architected has been a stepping stone to process 
  optimization, scalable architectures, and tangible growth.</p>

  <p>Yet, my passion transcends the realm of solution architecture. I wear the 
  badge of a mentor with pride, committing myself to the enlightenment of teams 
  and clients, ensuring that they harness the complete spectrum of technological 
  solutions.</p>

  <p>As this narrative culminates, I invite you to harness my expertise in 
  <strong>full-stack project design and development</strong>, with specialization 
  in <strong>GoLang</strong>, <strong>VueJS</strong>, and <strong>NuxtJS</strong>.</p>

  <p><strong>GoLang</strong>: Synonymous with efficiency, this statically typed, 
  compiled language, with its inherent performance and safety features, has 
  revolutionized back-end development.</p>

  <p><strong>VueJS</strong>: This progressive JavaScript framework has carved a 
  niche for itself in crafting intuitive user interfaces and single-page 
  applications, thanks to its versatility and performance.</p>

  <p><strong>NuxtJS</strong>: Built atop VueJS, this framework offers a bouquet 
  of features including server-side rendering and static site generation, 
  ensuring users always get a seamless experience.</p>

  <p>In summation, I'm grateful for your time and consideration. It's my 
  aspiration that we collaborate, leveraging my diverse skill set, and chart a 
  course towards unparalleled technological innovations.</p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/krizvi"
  #  resume_twitter_url:           "http://twitter.com/jglovier"
  #  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/khalidrizvi"
  resume_website_url:           "http://khalidrizvi.com"
  resume_medium_url:            "https://medium.com/@krizvi"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
