# Site settings
title: "Khalid Portfolio"
description: "An interactive showcase of Khalid Rizvi's extensive technical skills and experiences, hosted with Jekyll and GitHub Pages."


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "false"
resume_name: "Khalid Rizvi"
resume_title: "Excellence through innovation."

# used for the contact button in _layouts/resume.html
resume_contact_email: "khalid.rizvi@icloud.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "703-656-6394"
resume_contact_address: "9821 Spring Ridge Lane, Vienna, VA 22182"

resume_header_contact_info: "703-656-6394 • khalid.rizvi@icloud.com"
display_header_contact_info: "true"

resume_header_intro: >
  <p>As a seasoned Software Consultant, I excel at diagnosing intricate system 
  infrastructure issues in both on-premises and AWS cloud environments. My 
  proficiency shines particularly in 'lift and shift' migrations, and I take pride 
  in modernizing architectures using cloud-native patterns such as the strangler 
  pattern.</p>

  <p>My expertise runs deep in mentoring teams, driving rapid application 
  engineering, and formulating frameworks that curtail development time and costs. 
  My consistent focus has always been on delivering exceptional value to clients, 
  optimizing software designs for both business and private users.</p>

  <p>Among my key competencies, I am a hands-on programmer with guru-level 
  expertise in GoLang, Java, and JavaScript. My full-stack development prowess is 
  demonstrated using Vue3.js for SPAs and Nuxt.js for SSR. With a solid background 
  in Data Migration & Microservices Architecture, I have also championed cloud 
  solutions, mastering the 'Lift & Shift' from on-premises to AWS and excelling in 
  modernizing with cloud-native techniques. My familiarity with the AWS Suite is 
  comprehensive, encompassing tools such as Lambda, SQS, and DynamoDB, among 
  others. In the realm of DevOps & CI/CD, I am proficient with Jenkins, Docker, 
  OpenShift, and the AWS toolset, in addition to Azure DevOps with Boards on 
  Microsoft Azure cloud. My skill set also covers Security Solutions with a deep 
  understanding of Identity Management. Infrastructure as Code is another forte, 
  where I wield tools like Terraform, AWS SAM, and Ansible. Additionally, I have 
  substantial experience with monitoring and management tools, particularly AWS 
  CloudWatch and Jira.</p>

  <p>If you seek a dedicated partner to elevate your software solutions and infrastructure, 
  I would be honored to discuss how my expertise can benefit your endeavors.</p>



# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: false
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/krizvi"
  #  resume_twitter_url:           "http://twitter.com/jglovier"
  #  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/khalidrizvi"
  resume_website_url: "http://khalidrizvi.com"
  resume_medium_url: "https://medium.com/@krizvi"
resume_print_social_links: true

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
