# Site settings
title: "Portfolio of Mr. Khalid Rizvi"
description: "An interactive showcase of the extensive technical skills and experiences of Mr. Khalid Rizvi, hosted with Jekyll and GitHub Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "false"
resume_name: "Khalid Rizvi"
resume_title: "Excellence through innovation."

# used for the contact button in _layouts/resume.html
#resume_contact_email: "krizvi@dxc.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone: "703-656-6394"
#resume_contact_address: "9821 Spring Ridge Lane, Vienna, VA 22182"

resume_header_contact_info: "703-656-6394 • khalid.rizvi@icloud.com"
display_header_contact_info: "false"

resume_header_intro: >
  <p>Mr. Khalid Rizvi, a seasoned Technology Architect, has extensive experience in
  various industries such as transportation, fintech, and healthcare. He specializes
  in designing and implementing large-scale software applications, using
  technologies like Dell Boomi, GoLang, ReactJS, Java, Scala and more. His
  record of leading technical teams and resolving complex business problems
  is underpinned by his ability to understand new business domains and
  technological landscapes swiftly. He has a proven track record in building
  strong stakeholder relationships, driving investment decisions, and
  articulating complex technical solutions to diverse audiences. His
  leadership style encourages team autonomy, fostering independent planning
  and execution. A determined, strategic, and effective leader, he is adept
  at steering projects to successful completion while staying updated with
  cutting-edge technologies. His expertise extends to AI/ML, Model
  Transformation, and managing third-party software upgrades, aligning with
  the latest industry requirements and standards.</p>  

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "no"

# Decide which sections to use
# comment out to hide
resume_section_experience: false
resume_section_education: false
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: false
resume_section_associations: false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/krizvi"
  #  resume_twitter_url:           "http://twitter.com/jglovier"
  #  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/khalidrizvi"
#  resume_website_url: "http://khalidrizvi.com"
  resume_medium_url: "https://medium.com/@krizvi"
resume_print_social_links: true

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
