# Site settings
title: "Jarry Portfolio"
description: "An interactive showcase of Khalid Rizvi's extensive technical skills and experiences, hosted with Jekyll and GitHub Pages."


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "false"
resume_name: "Jarry Rizvi"
resume_title: "Innovator. Developer. Trailblazer."

# used for the contact button in _layouts/resume.html
resume_contact_email: "jarry.a.rizvi@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "(917) 378-4885"
resume_contact_address: "Hicksville, NY 11040"

resume_header_contact_info: "(917) 378-4885 • jarry.a.rizvi@gmail.com"
display_header_contact_info: "true"

Summary:
resume_header_intro: >
  <p>As a seasoned <strong>Full Stack Developer</strong> and 
  <strong>Cloud Engineer</strong> with over <strong>5 years</strong> of 
  experience, I possess a deep-rooted passion for cloud technologies and 
  innovation. With certifications in <strong>AWS Solutions Architect- 
  Associate</strong> and <strong>CompTIA Security+ ce</strong>, I've 
  demonstrated a consistent ability to devise and implement cutting-edge 
  solutions that drive operational excellence.</p>

  <p>My proactive approach, combined with my expertise as a mobile native 
  developer, equips me to address intricate challenges with precision. 
  I'm eager to collaborate with a forward-thinking AWS DevOps team 
  comprising of doers, where I can further harness my skills to architect 
  and deploy scalable, secure cloud solutions. In pursuit of this vision, 
  I'm actively seeking opportunities in the realm of solution DevOps on 
  the AWS platform, aiming to contribute meaningfully and foster 
  innovation in the cloud domain.</p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: false
resume_section_skills: true
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false
resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
#resume_social_links:
#  resume_github_url: "https://github.com/krizvi"
#  #  resume_twitter_url:           "http://twitter.com/jglovier"
#  #  resume_dribbble_url:          "https://dribbble.com/jag"
#  # resume_facebook_url:          "insert Facebook URL here"
#  # resume_instagram_url:         "insert your Instagram URL here"
#  resume_linkedin_url: "https://www.linkedin.com/in/khalidrizvi"
#  resume_website_url: "http://khalidrizvi.com"
#  resume_medium_url: "https://medium.com/@krizvi"
#resume_print_social_links: false

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
